### ISSUE TITLE
The remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by Oliezhensev** [microsoft/AICentral#113]
When we start service on AKS using Azure private endpoints, we got this error:
`[08:21:19 ERR] Failed to handle request
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ReadOnlySpan`1 alert, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
`
Configuration file:
`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning",
      "AICentralApi": "Debug"
    }
  },
  "WEBSITES_PORT": "8080",
  "APPLICATIONINSIGHTS_CONNECTION_STRING": "InstrumentationKey=<connection_string>",
  "APPINSIGHTS_INSTRUMENTATIONKEY": "<key>",
  "AllowedHosts": "*",
  "AICentral": {
    "Endpoints": [
      {
        "Type": "AzureOpenAIEndpoint",
        "Name": "openai-1",
        "Properties": {
            "LanguageEndpoint": "https://<deployment_name>.privatelink.cognitiveservices.azure.com/",
            "ModelMappings": {
              "gpt-35-turbo": "gpt_35_turbo",
              "gpt-4": "gpt_4_turbo",
              "text-embedding-ada-002": "text-embedding-ada-002",
              "text-embedding-3-large": "text_embedding_3_large"
            },
            "EnforceMappedModels": true,
            "AuthenticationType": "ApiKey",
            "ApiKey": "<ApiKey>",
            "MaxConcurrency": 5,
            "AutoPopulateEmptyUserId": true
        }
    }
    ],
    "EndpointSelectors": [
      {
        "Type": "SingleEndpoint",
        "Name": "default",
        "Properties": {
          "Endpoint": "openai-1"
        }
      }
    ],
    "GenericSteps": [
      {
        "Type": "AspNetCoreFixedWindowRateLimiting",
        "Name": "window-rate-limiter",
        "Properties": {
          "LimitType": "PerAICentralEndpoint",
          "MetricType": "Requests",
          "Options": {
            "Window": "00:00:10",
            "PermitLimit": 100
          }
        }
      },
      {
        "Type": "AzureMonitorLogger",
        "Name": "azure-monitor-logger",
        "Properties": {
          "WorkspaceId": "dev-eastus",
          "Key": "<key>",
          "LogPrompt": true,
          "LogResponse": false,
          "LogClient": true
        }
      }
    ],
    "AuthProviders": [
      {
        "Type": "AllowAnonymous",
        "Name": "no-auth"
      }
    ],
    "Pipelines": [
      {
        "Name": "MyPipeline",
        "Host": "*",
        "EndpointSelector": "default",
        "AuthProvider": "no-auth"
      }
    ]
  }
}`

**Comment by graemefoster** [comment]
@Oliezhensev change the language endpoint from 
https://<deployment_name>.privatelink.cognitiveservices.azure.com

To

https://<deployment_name>.cognitiveservices.azure.com

private endpoints cname the primary host name to the private link version. The open ai service presents the original host name on its carts. 

Thanks,
Graeme

**Comment by iamp3** [comment]
> @Oliezhensev change the language endpoint from https://<deployment_name>.privatelink.cognitiveservices.azure.com
> 
> To
> 
> https://<deployment_name>.cognitiveservices.azure.com
> 
> private endpoints cname the primary host name to the private link version. The open ai service presents the original host name on its carts.
> 
> Thanks, Graeme

Hi @graemefoster 

Its looks like we could reach-out private endpoints, but overall requests failed. We tried to revert to public endpoint and I see this error on my curl requests that were succeed yesterday 

```json
{"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
```

Could you advice why it happend and how we could fix it? I dont see any changes on ApiKey or Public Endpoints

**Comment by graemefoster** [comment]
@Oliezhensev I've added diagnostics on startup into the latest release. AI Central will output a bunch of information about the Open AI endpoint. IP address, certificate, anything that smells wrong, along with suggestions on what needs to be changed.
Please can you update to 0.16.21 and retry.

**Comment by iamp3** [comment]
> @Oliezhensev I've added diagnostics on startup into the latest release. AI Central will output a bunch of information about the Open AI endpoint. IP address, certificate, anything that smells wrong, along with suggestions on what needs to be changed. Please can you update to 0.16.21 and retry.

Hi @graemefoster, thanks for updates. 

Just to clarify:
Private Link -> A record to our OpenAI endpoint in format $domain_name.privatelink.openai.azure.com
Correct Language domain in app config should be -> CNAME to Private Link in format $domain_name.openai.azure.com

Is it correct?

**Comment by graemefoster** [comment]
@Oliezhensev when you enable private link on a service what happens is add a CNAME to the primary hostname, with the one with privatelink in it. You can see it by doing a dig, or other dns lookup on the primary hostname.

It's then up to you to manage the A Record against the private-link hostname. You can use our "DNS Zone Group" to do this on an Azure private DNS Zone, or you can manage it in your own DNS servers.

Hope that clarifies.

**Comment by graemefoster** [comment]
You need an A Record for 'myaoairesource.privatelink.openai.azure.com' pointing to the private IP address.

But when you specify the hostname to AICEntral in config, just pass 'myaoairesource.openai.azure.com' and let DNS work out to resolve against 'myaoairesource.privatelink.openai.azure.com'

**Comment by iamp3** [comment]
> You need an A Record for 'myaoairesource.privatelink.openai.azure.com' pointing to the private IP address.
> 
> But when you specify the hostname to AICEntral in config, just pass 'myaoairesource.openai.azure.com' and let DNS work out to resolve against 'myaoairesource.privatelink.openai.azure.com'

When we create OpenAI service with private endpoint enabled we got this DNS records created:
`nslookup $domain_name.openai.azure.com

Address:  $public_ip
Aliases:  $domain_name.openai.azure.com
          $domain_name.privatelink.openai.azure.com`
          
If I check $domain_name.privatelink.openai.azure.com via nslookup, I got public IP instead of private, is it expected? if yes, I should create A record for $domain_name.privatelink.openai.azure.com -> private_ip manually?

**Comment by graemefoster** [comment]
The key is how it’s seen from your aks server - not the public. Normally the private link leads to NXDOMAIN if you try resolve it from outside your network. 

From within an azure vnet, as long as you’ve attached the private dns zone to the vnet, it should resolve as expected. 

If you run the latest version of ai central then check the logs. It will give you all the information that should help debug things.

**Comment by iamp3** [comment]
> The key is how it’s seen from your aks server - not the public. Normally the private link leads to NXDOMAIN if you try resolve it from outside your network.
> 
> From within an azure vnet, as long as you’ve attached the private dns zone to the vnet, it should resolve as expected.
> 
> If you run the latest version of ai central then check the logs. It will give you all the information that should help debug things.

Thanks for help, looks like we found an issue with record creation and now it works expectedly throw private endpoints.
